In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_wine

wine = load_wine()
df = pd.DataFrame(data=wine.data, columns=wine.feature_names)
df['target'] = wine.target

In [3]:
df.target.value_counts()

1    71
0    59
2    48
Name: target, dtype: int64

In [4]:
X = df.drop(columns=['target'])
y = df.target

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [8]:
y_pred = model.predict(X_test)

In [9]:
y_pred

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 2,
       2])

In [10]:
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc: .2f}")

conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix: ')
print(conf_matrix)

class_report = classification_report(y_test, y_pred)
print("Classification Report: ")
print(class_report)

Accuracy:  0.98
Confusion Matrix: 
[[15  0  0]
 [ 0 17  1]
 [ 0  0 12]]
Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        12

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



# Hyperparameter Tuning

In [11]:
param_grid = {
    'C' : [0.001, 0.01, 1, 10, 100, 1000],
    'penalty' : ['l1', 'l2', 'elastic', 'none'],
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
}

In [12]:
model = LogisticRegression()

In [13]:
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')

In [14]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 1, 10, 100, 1000],
                         'penalty': ['l1', 'l2', 'elastic', 'none'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [15]:
best_params = grid_search.best_params_

In [16]:
best_params

{'C': 0.001, 'penalty': 'none', 'solver': 'saga'}

In [17]:
best_estimator = grid_search.best_estimator_

In [18]:
y_pred = best_estimator.predict(X_test)

In [19]:
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc: .2f}")

conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix: ')
print(conf_matrix)

class_report = classification_report(y_test, y_pred)
print("Classification Report: ")
print(class_report)

Accuracy:  0.98
Confusion Matrix: 
[[15  0  0]
 [ 0 17  1]
 [ 0  0 12]]
Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        12

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

