In [1]:
import pickle 
import numpy as np

In [15]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('model/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('model/clf.pkl', 'rb'))

In [16]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [17]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1,1))

C:\Users\csawa\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [18]:
test_input_sex

array([[0., 1.]])

In [21]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [22]:
test_input_embarked

array([[0., 0., 1.]])

In [25]:
test_input_transformed = np.concatenate((test_input[:, [0,2,3,4,5]], test_input_sex, test_input_embarked), axis=1)

In [26]:
test_input_transformed.shape

(1, 10)

In [27]:
clf.predict(test_input_transformed)

array([1], dtype=int64)